# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 19:57
from __future__ import unicode_literals

import customers.models
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(-1, b'Eliminado'), (0, b'Inactivo'), (1, b'Activo')], default=1, max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(null=True)),
                ('deleted_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('createdby_id', models.IntegerField(default=0)),
                ('modifiedby_id', models.IntegerField(default=0)),
                ('synckey', models.CharField(default=b'', max_length=512)),
                ('name', models.CharField(max_length=140)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street', models.CharField(max_length=140, null=True)),
                ('colony', models.CharField(max_length=140, null=True)),
                ('nostreet', models.IntegerField(blank=True, default=0, null=True)),
                ('zipcode', models.IntegerField(default=0, null=True)),
                ('country', models.CharField(default=b'', max_length=5)),
                ('logo', models.ImageField(blank=True, upload_to=customers.models.customer_filename)),
                ('notes', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'customers',
            },
        ),
    ]
