# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 19:57
from __future__ import unicode_literals

import accounts.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('status', models.CharField(choices=[(-1, b'Eliminado'), (0, b'Inactivo'), (1, b'Activo')], default=1, max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_date', models.DateTimeField(null=True)),
                ('deleted_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('createdby_id', models.IntegerField(default=0)),
                ('modifiedby_id', models.IntegerField(default=0)),
                ('synckey', models.CharField(default=b'', max_length=512)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, upload_to=accounts.models.user_filename)),
                ('user_type', models.CharField(choices=[(b'SA', b'Super Admin'), (b'C', b'Admin Agricola'), (b'G', b'Gerente'), (b'TI', b'Tecnico Interno'), (b'TE', b'Tecnico Externo'), (b'NA', b'Sin Acceso')], default=b'A', max_length=2)),
                ('api_token', models.CharField(default=b'', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=15)),
                ('action', models.CharField(max_length=256)),
                ('time_request', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_actions',
            },
        ),
        migrations.CreateModel(
            name='UserModulePermanence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition_type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=15)),
                ('use_proxy', models.BooleanField(default=False)),
                ('time_request_init', models.DateTimeField(auto_now_add=True)),
                ('time_request_out', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_module_permanence',
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('expires_key', models.DateTimeField(default=datetime.datetime.now)),
                ('activation_type', models.CharField(choices=[(1, b'Activacion'), (2, b'Solicitud Password'), (3, b'Invitacion')], default=b'1', max_length=2)),
                ('activation_status', models.CharField(choices=[(-1, b'Expirado'), (0, b'Enviado'), (1, b'Activado')], default=b'0', max_length=2)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_request',
            },
        ),
    ]
